GF256_MAX_SHARES = 255

ETHERNET_MTU_BYTES = 1500
IP_HEADER_BYTES = 20
UDP_HEADER_BYTES = 8
FRAME_PREFIX_BYTES = 12
PROTOBUF_OVERHEAD_BYTES = 18
MAX_SYMBOL_BYTES = (
    ETHERNET_MTU_BYTES
    - IP_HEADER_BYTES
    - UDP_HEADER_BYTES
    - FRAME_PREFIX_BYTES
    - PROTOBUF_OVERHEAD_BYTES
)

DEFAULT_RATE_CEILING_BPS = 20_000_000
DEFAULT_RATE_FLOOR_BPS = 5_000_000

PATHS_SECTION = "paths"
PACING_SECTION = "pacing"
FEC_SECTION = "fec"

WATCH_PATH_KEY = "watch_path"
SOCKET_PATH_KEY = "socket_path"
RATE_CEILING_BPS_KEY = "rate_ceiling_bps"
RATE_FLOOR_BPS_KEY = "rate_floor_bps"
FEC_K_KEY = "k"
FEC_N_KEY = "n"
FEC_SYMBOL_BYTES_KEY = "symbol_bytes"

WATCH_PATH_ENV_VAR = "WATCH_PATH"
SOCKET_PATH_ENV_VAR = "SOCKET_PATH"
RATE_CEILING_BPS_ENV_VAR = "RATE_CEILING_BPS"
RATE_FLOOR_BPS_ENV_VAR = "RATE_FLOOR_BPS"
FEC_K_ENV_VAR = "FEC_K"
FEC_N_ENV_VAR = "FEC_N"
FEC_SYMBOL_BYTES_ENV_VAR = "FEC_SYMBOL_BYTES"

NEXUS_CONFIG_ENV_VAR = "NEXUS_CONFIG"
DEFAULT_CONFIG_PATH = "config.toml"

PROTO_CONTRACT_DIR = "libs/nexus-proto/proto"

# Placeholder composition-root wiring: no config field or real sender binary
# exists yet for these. Replace once per-deployment sender configuration and
# the C++ sender binary are available.
SENDER_COUNT = 3
SENDER_BINARY_PATH = "./bin/nexus-sender"
DEFAULT_TARGET_HOST = "127.0.0.1"
DEFAULT_BASE_PORT = 9000
