GF256_MAX_SHARES = 255

ETHERNET_MTU_BYTES = 1500
IP_HEADER_BYTES = 20
UDP_HEADER_BYTES = 8
FRAME_PREFIX_BYTES = 12
PROTOBUF_OVERHEAD_BYTES = 18
MAX_SYMBOL_BYTES = (
    ETHERNET_MTU_BYTES
    - IP_HEADER_BYTES
    - UDP_HEADER_BYTES
    - FRAME_PREFIX_BYTES
    - PROTOBUF_OVERHEAD_BYTES
)

DEFAULT_RATE_CEILING_BPS = 20_000_000
DEFAULT_RATE_FLOOR_BPS = 5_000_000

PATHS_SECTION = "paths"
PACING_SECTION = "pacing"
FEC_SECTION = "fec"
SENDERS_SECTION = "senders"

WATCH_PATH_KEY = "watch_path"
SOCKET_PATH_KEY = "socket_path"
RATE_CEILING_BPS_KEY = "rate_ceiling_bps"
RATE_FLOOR_BPS_KEY = "rate_floor_bps"
FEC_K_KEY = "k"
FEC_N_KEY = "n"
FEC_SYMBOL_BYTES_KEY = "symbol_bytes"
TARGET_HOST_KEY = "target_host"
BASE_PORT_KEY = "base_port"
BINARY_PATH_KEY = "binary_path"
SENDER_COUNT_KEY = "sender_count"

# NEXUS_-namespaced to avoid collisions in a shared compose stack.
WATCH_PATH_ENV_VAR = "NEXUS_WATCH_PATH"
SOCKET_PATH_ENV_VAR = "NEXUS_SOCKET_PATH"
RATE_CEILING_BPS_ENV_VAR = "NEXUS_RATE_CEILING_BPS"
RATE_FLOOR_BPS_ENV_VAR = "NEXUS_RATE_FLOOR_BPS"
FEC_K_ENV_VAR = "NEXUS_FEC_K"
FEC_N_ENV_VAR = "NEXUS_FEC_N"
FEC_SYMBOL_BYTES_ENV_VAR = "NEXUS_FEC_SYMBOL_BYTES"
TARGET_HOST_ENV_VAR = "NEXUS_SENDERS_TARGET_HOST"
BASE_PORT_ENV_VAR = "NEXUS_SENDERS_BASE_PORT"
BINARY_PATH_ENV_VAR = "NEXUS_SENDERS_BINARY_PATH"
SENDER_COUNT_ENV_VAR = "NEXUS_SENDERS_SENDER_COUNT"

NEXUS_CONFIG_ENV_VAR = "NEXUS_CONFIG"
DEFAULT_CONFIG_PATH = "config.toml"

PROTO_CONTRACT_DIR_ENV_VAR = "NEXUS_PROTO_CONTRACT_DIR"
DEFAULT_PROTO_CONTRACT_DIR = "libs/nexus-proto/proto"

DEFAULT_TARGET_HOST = "127.0.0.1"
DEFAULT_BASE_PORT = 9000
DEFAULT_SENDER_BINARY_PATH = "./bin/nexus-sender"
DEFAULT_SENDER_COUNT = 3

MIN_PORT = 1
MAX_PORT = 65535

CONFIG_ERROR_EXIT_CODE = 78  # sysexits.h EX_CONFIG
